# .readthedocs.yaml
# Read the Docs configuration file for CJE documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry for main package
      - pip install poetry
    post_install:
      # Install main package dependencies
      - poetry config virtualenvs.create false
      - poetry install --only main

# Python configuration for docs dependencies
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Set the formats you want to build
formats: 
  - htmlzip
  - pdf
  - epub 