# .readthedocs.yaml
# Read the Docs configuration file for CJE documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
    post_install:
      # Install docs dependencies first
      - pip install -r docs/requirements.txt
      # Install numpy explicitly first to avoid import issues
      - pip install numpy
      # Install package and dependencies with poetry 
      - poetry config virtualenvs.create false
      - poetry install --with dev --no-interaction

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# Set the formats you want to build
formats: 
  - htmlzip
  - pdf
  - epub 